name: archimedes_bridge
description: "Simple flutter game"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #general
  flame: ^1.11.0
  flame_tiled: ^1.18.0
  flame_forge2d: ^0.16.0+1
  flutter_bloc: ^8.1.3

  #ui

  #utils
  cupertino_icons: ^1.0.2
  rxdart: 0.27.7
  auto_route: ^7.8.4
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2

  lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/sprites/
    - assets/images/
    - assets/music/
